name: SouthEscape
favicon: null
layout_spectrum: 0.9408195349387825
typography_spectrum: 0.7144927324261516
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9103972930461168
  lightness: 0.6667289179749787
  saturation: 0.1832571909762919
  rhythmicContrast: 0.5815443289466202
purpose: []
