name: SouthEscape
favicon: null
layout_spectrum: 0.8840064937248826
typography_spectrum: 0.43110106978565454
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5779657023958862
  lightness: 0.13125708675943315
  saturation: 0.6039355397224426
  rhythmicContrast: 0.605859178584069
purpose: []
