name: SouthEscape
favicon: null
layout_spectrum: 0.05734160519205034
typography_spectrum: 0.7120865457691252
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8887033173814416
  lightness: 0.4573636665008962
  saturation: 0.43513275450095534
  rhythmicContrast: 0.0684988226275891
purpose: []
