name: SouthEscape
favicon: null
layout_spectrum: 0.28589848056435585
typography_spectrum: 0.32126702670939267
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.43710389197804034
  lightness: 0.27765878080390394
  saturation: 0.6007045838050544
  rhythmicContrast: 0.5360210840590298
purpose: []
