name: SouthEscape
favicon: null
layout_spectrum: 0.98828069656156
typography_spectrum: 0.7584726351778954
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7727860433515161
  lightness: 0.24549453798681498
  saturation: 0.9336101843509823
  rhythmicContrast: 0.9058618727140129
purpose: []
