name: SouthEscape
favicon: null
layout_spectrum: 0.9408195349387825
typography_spectrum: 0.7144927324261516
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0e1800'
    - '#b6b5b0'
    - '#4f463d'
    - '#a78e6f'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
