name: SouthEscape
favicon: null
layout_spectrum: 0.361009550280869
typography_spectrum: 0.7638572987634689
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.02271780534647405
  lightness: 0.10288395336829126
  saturation: 0.8367492468096316
  rhythmicContrast: 0.8922854936681688
purpose: []
